/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { userSchema } from "@repo/schemas";

const appRouter = t.router({
  example: t.router({
    getTodos: publicProcedure
      .output(z.array(z.object({ id: z.number(), name: z.string() })))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createUser: publicProcedure
      .input(userSchema)
      .output(userSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getUsers: publicProcedure
      .output(z.array(userSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
