/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from '@trpc/server';
import superjson from 'superjson';

const t = initTRPC.create({ transformer: superjson });
const publicProcedure = t.procedure;
import {
  createUserSchema,
  userSchema,
  updateUserSchema,
  deleteUserSchema,
  userCreatedSubscriptionSchema,
  userUpdatedSubscriptionSchema,
  userDeletedSubscriptionSchema,
} from '@repo/schemas/users';

const appRouter = t.router({
  users: t.router({
    createUser: publicProcedure
      .input(createUserSchema)
      .output(userSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    getUsers: publicProcedure
      .output(userSchema.array())
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    updateUser: publicProcedure
      .input(updateUserSchema)
      .output(userSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    deleteUser: publicProcedure
      .input(deleteUserSchema)
      .output(userSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    onUserCreated: publicProcedure
      .output(userCreatedSubscriptionSchema)
      .subscription(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    onUserUpdated: publicProcedure
      .output(userUpdatedSubscriptionSchema)
      .subscription(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    onUserDeleted: publicProcedure
      .output(userDeletedSubscriptionSchema)
      .subscription(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
});

export type AppRouter = typeof appRouter;
