/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from '@trpc/server';
import { z } from 'zod';
import superjson from 'superjson';

const t = initTRPC.create({ transformer: superjson });
const publicProcedure = t.procedure;
import {
  eventSortSchema,
  eventsSchema,
  createEventSchema,
  createEventResultSchema,
  eventIdSchema,
  updateEventSchema,
  eventSchema,
  deleteEventSchema,
} from '@repo/schemas/events';
import { eventStatsSchema } from '@repo/schemas/stats';
import {
  userSchema,
  createUserSchema,
  updateUserSchema,
  adminUpdateUserSchema,
  deleteUserSchema,
  userCreatedSubscriptionSchema,
  userUpdatedSubscriptionSchema,
  userDeletedSubscriptionSchema,
} from '@repo/schemas/users';
import { addFriendSchema, friendSchema, removeFriendSchema } from '@repo/schemas/friends';
import { getOnlineUserIdsSchema, presenceChangedSubscriptionSchema } from '@repo/schemas/presence';
import type { EventsRouter } from '/home/muijf/ft_transcendence/apps/backend/src/events/events.router';

const appRouter = t.router({
  events: t.router({
    getEvents: publicProcedure
      .input(eventSortSchema)
      .output(eventsSchema)
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    getFeaturedEvents: publicProcedure
      .output(eventsSchema)
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    getEventStats: publicProcedure
      .output(eventStatsSchema)
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
  eventCreation: t.router({
    createEvent: publicProcedure
      .input(createEventSchema)
      .output(createEventResultSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    getEventById: publicProcedure
      .input(eventIdSchema)
      .query(
        async () =>
          'PLACEHOLDER_DO_NOT_REMOVE' as unknown as Awaited<
            ReturnType<EventsRouter['getEventById']>
          >,
      ),
    updateEvent: publicProcedure
      .input(updateEventSchema)
      .output(eventSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    deleteEvent: publicProcedure
      .input(deleteEventSchema)
      .output(eventSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
  friends: t.router({
    getFriends: publicProcedure
      .output(userSchema.array())
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    getPendingRequests: publicProcedure
      .output(userSchema.array())
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    addFriend: publicProcedure
      .input(addFriendSchema)
      .output(friendSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    acceptFriend: publicProcedure
      .input(addFriendSchema)
      .output(friendSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    removeFriend: publicProcedure
      .input(removeFriendSchema)
      .output(friendSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
  presence: t.router({
    getOnlineUserIds: publicProcedure
      .input(getOnlineUserIdsSchema)
      .output(z.uuid().array())
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    onPresenceChanged: publicProcedure
      .output(presenceChangedSubscriptionSchema)
      .subscription(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
  registrations: t.router({}),
  users: t.router({
    createUser: publicProcedure
      .input(createUserSchema)
      .output(userSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    getUsers: publicProcedure
      .output(userSchema.array())
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    getMe: publicProcedure
      .output(userSchema.nullable())
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    updateUser: publicProcedure
      .input(updateUserSchema)
      .output(userSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    adminUpdateUser: publicProcedure
      .input(adminUpdateUserSchema)
      .output(userSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    deleteUser: publicProcedure
      .input(deleteUserSchema)
      .output(userSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    onUserCreated: publicProcedure
      .output(userCreatedSubscriptionSchema)
      .subscription(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    onUserUpdated: publicProcedure
      .output(userUpdatedSubscriptionSchema)
      .subscription(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    onUserDeleted: publicProcedure
      .output(userDeletedSubscriptionSchema)
      .subscription(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
});

export type AppRouter = typeof appRouter;
