export interface EventCancellationEmailDictionary {
  previewText: string;
  subjectText: string;
  greeting: string;
  description: string;
  detailsHeader: string;
  labelEvent: string;
  labelDateTime: string;
  labelLocation: string;
  buttonLabel: string;
  footerNotice: string;
}

export const eventCancellationTranslations: Record<
  'en' | 'nl' | 'es' | 'ru' | 'ro',
  EventCancellationEmailDictionary
> = {
  en: {
    previewText: 'Important update: An upcoming event has been cancelled.',
    subjectText: 'Event Cancelled:',
    greeting: 'Notice regarding your upcoming event, {userName}',
    description:
      'We are writing to inform you that the upcoming event listed below has been cancelled by the organizer. Your registration has been automatically voided and your spot released.',
    detailsHeader: 'Cancelled Event Details',
    labelEvent: 'Event',
    labelDateTime: 'Date & Time',
    labelLocation: 'Location',
    buttonLabel: 'Explore Other Events',
    footerNotice:
      'This message was automatically generated by Eventra. If you have questions regarding the cancellation, please contact the event organizer directly.',
  },
  nl: {
    previewText: 'Important update: An upcoming event has been cancelled. (NL Placeholder)',
    subjectText: 'Event Cancelled: (NL Placeholder)',
    greeting: 'Notice regarding your upcoming event, {userName} (NL Placeholder)',
    description:
      'We are writing to inform you that the upcoming event listed below has been cancelled by the organizer. Your registration has been automatically voided and your spot released. (NL Placeholder)',
    detailsHeader: 'Cancelled Event Details (NL Placeholder)',
    labelEvent: 'Event (NL Placeholder)',
    labelDateTime: 'Date & Time (NL Placeholder)',
    labelLocation: 'Location (NL Placeholder)',
    buttonLabel: 'Explore Other Events (NL Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If you have questions regarding the cancellation, please contact the event organizer directly. (NL Placeholder)',
  },
  es: {
    previewText: 'Aviso importante: Se ha cancelado un próximo evento.',
    subjectText: 'Evento Cancelado:',
    greeting: 'Aviso sobre tu próximo evento, {userName}',
    description:
      'Te informamos que el evento indicado a continuación ha sido cancelado por el organizador. Tu registro ha quedado anulado de forma automática en nuestro sistema y tu plaza ha sido liberada.',
    detailsHeader: 'Detalles del Evento Cancelado',
    labelEvent: 'Espectáculo',
    labelDateTime: 'Fecha y Hora',
    labelLocation: 'Ubicación',
    buttonLabel: 'Explorar Otros Eventos',
    footerNotice:
      'Este mensaje ha sido generado automáticamente por Eventra. Si tienes alguna duda sobre la cancelación, por favor ponte en contacto directo con el organizador del evento.',
  },
  ru: {
    previewText: 'Important update: An upcoming event has been cancelled. (RU Placeholder)',
    subjectText: 'Event Cancelled: (RU Placeholder)',
    greeting: 'Notice regarding your upcoming event, {userName} (RU Placeholder)',
    description:
      'We are writing to inform you that the upcoming event listed below has been cancelled by the organizer. Your registration has been automatically voided and your spot released. (RU Placeholder)',
    detailsHeader: 'Cancelled Event Details (RU Placeholder)',
    labelEvent: 'Event (RU Placeholder)',
    labelDateTime: 'Date & Time (RU Placeholder)',
    labelLocation: 'Location (RU Placeholder)',
    buttonLabel: 'View My Tickets (RU Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If you have questions regarding the cancellation, please contact the event organizer directly. (RU Placeholder)',
  },
  ro: {
    previewText: 'Important update: An upcoming event has been cancelled. (RO Placeholder)',
    subjectText: 'Event Cancelled: (RO Placeholder)',
    greeting: 'Notice regarding your upcoming event, {userName} (RO Placeholder)',
    description:
      'We are writing to inform you that the upcoming event listed below has been cancelled by the organizer. Your registration has been automatically voided and your spot released. (RO Placeholder)',
    detailsHeader: 'Cancelled Event Details (RO Placeholder)',
    labelEvent: 'Event (RO Placeholder)',
    labelDateTime: 'Date & Time (RO Placeholder)',
    labelLocation: 'Location (RO Placeholder)',
    buttonLabel: 'Explore Other Events (RO Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If you have questions regarding the cancellation, please contact the event organizer directly. (RO Placeholder)',
  },
};
