export interface EventModificationEmailDictionary {
  previewText: string;
  subjectText: string;
  greeting: string;
  description: string;
  detailsHeader: string;
  labelEvent: string;
  labelDateTime: string;
  labelLocation: string;
  buttonLabel: string;
  footerNotice: string;
}

export const eventModificationTranslations: Record<
  'en' | 'nl' | 'es' | 'ru',
  EventModificationEmailDictionary
> = {
  en: {
    previewText: 'Important agenda update: An event you are attending has changed.',
    subjectText: 'Event Updated:',
    greeting: 'Event update for {userName}',
    description:
      'We are writing to let you know that an upcoming event on your list has been modified by the organizer. Please review the updated details below.',
    detailsHeader: 'Updated Details',
    labelEvent: 'Event',
    labelDateTime: 'Date & Time',
    labelLocation: 'Location',
    buttonLabel: 'View Event Details',
    footerNotice:
      'This message was automatically generated by Eventra. If these changes conflict with your availability, you can manage or cancel your ticket via your dashboard.',
  },
  nl: {
    previewText:
      'Important agenda update: An event you are attending has changed. (NL Placeholder)',
    subjectText: 'Event Updated: (NL Placeholder)',
    greeting: 'Event update for {userName} (NL Placeholder)',
    description:
      'We are writing to let you know that an upcoming event on your list has been modified by the organizer. Please review the updated details below. (NL Placeholder)',
    detailsHeader: 'Updated Details (NL Placeholder)',
    labelEvent: 'Event (NL Placeholder)',
    labelDateTime: 'Date & Time (NL Placeholder)',
    labelLocation: 'Location (NL Placeholder)',
    buttonLabel: 'View Event Details (NL Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If these changes conflict with your availability, you can manage or cancel your ticket via your dashboard. (NL Placeholder)',
  },
  es: {
    previewText: 'Actualización importante de tu agenda: Un evento al que asistirás ha cambiado.',
    subjectText: 'Evento Actualizado:',
    greeting: 'Aviso de actualización para {userName}',
    description:
      'Te informamos de que el organizador ha modificado los detalles de un evento al que estás inscrito. Por favor, revisa la información actualizada a continuación.',
    detailsHeader: 'Detalles Actualizados',
    labelEvent: 'Evento',
    labelDateTime: 'Fecha y Hora',
    labelLocation: 'Ubicación',
    buttonLabel: 'Ver Detalles del Evento',
    footerNotice:
      'Este mensaje ha sido generado automáticamente por Eventra. Si este cambio te impide asistir, puedes gestionar o cancelar tu entrada desde tu panel de control.',
  },
  ru: {
    previewText:
      'Important agenda update: An event you are attending has changed. (RU Placeholder)',
    subjectText: 'Event Updated: (RU Placeholder)',
    greeting: 'Event update for {userName} (RU Placeholder)',
    description:
      'We are writing to let you know that an upcoming event on your list has been modified by the organizer. Please review the updated details below. (RU Placeholder)',
    detailsHeader: 'Updated Details (RU Placeholder)',
    labelEvent: 'Event (RU Placeholder)',
    labelDateTime: 'Date & Time (RU Placeholder)',
    labelLocation: 'Location (RU Placeholder)',
    buttonLabel: 'View Event Details (RU Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If these changes conflict with your availability, you can manage or cancel your ticket via your dashboard. (RU Placeholder)',
  },
};
