export interface EventCancellationEmailDictionary {
  previewText: string;
  subjectText: string;
  greeting: string;
  description: string;
  detailsHeader: string;
  labelEvent: string;
  labelDateTime: string;
  labelLocation: string;
  buttonLabel: string;
  footerNotice: string;
}

export const eventCancellationTranslations: Record<
  'en' | 'nl' | 'es',
  EventCancellationEmailDictionary
> = {
  en: {
    previewText: 'Important update: An upcoming event has been cancelled.',
    subjectText: 'Event Cancelled:',
    greeting: 'Notice regarding your upcoming event, {userName}',
    description:
      'We are writing to inform you that the upcoming event listed below has been cancelled by the organizer. Your registration has been automatically deleted.',
    detailsHeader: 'Cancelled Event Details',
    labelEvent: 'Event',
    labelDateTime: 'Date & Time',
    labelLocation: 'Location',
    buttonLabel: 'Explore Other Events',
    footerNotice:
      'This message was automatically generated by Eventra. If you have questions regarding the cancellation, please contact the event organizer directly.',
  },
  nl: {
    previewText: 'Belangrijke update: Een aankomend evenement is geannuleerd.',
    subjectText: 'Evenement geannuleerd:',
    greeting: 'Bericht over je aankomende evenement, {userName}',
    description:
      'We willen je laten weten dat het onderstaande aankomende evenement door de organisator is geannuleerd. Je inschrijving is automatisch verwijderd.',
    detailsHeader: 'Details van het geannuleerde evenement',
    labelEvent: 'Evenement',
    labelDateTime: 'Datum & tijd',
    labelLocation: 'Locatie',
    buttonLabel: 'Ontdek andere evenementen',
    footerNotice:
      'Dit bericht is automatisch gegenereerd door Eventra. Als je vragen hebt over de annulering, neem dan rechtstreeks contact op met de organisator van het evenement.',
  },
  es: {
    previewText: 'Aviso importante: Se ha cancelado un próximo evento.',
    subjectText: 'Evento cancelado:',
    greeting: 'Aviso sobre tu próximo evento, {userName}',
    description:
      'Te informamos que el evento indicado a continuación ha sido cancelado por el organizador. Tu registro ha sido eliminado automáticamente.',
    detailsHeader: 'Detalles del evento cancelado',
    labelEvent: 'Espectáculo',
    labelDateTime: 'Fecha y hora',
    labelLocation: 'Ubicación',
    buttonLabel: 'Explorar otros eventos',
    footerNotice:
      'Este mensaje ha sido generado automáticamente por Eventra. Si tienes alguna duda sobre la cancelación, por favor ponte en contacto directo con el organizador del evento.',
  },
};
