export interface EventModificationEmailDictionary {
  previewText: string;
  subjectText: string;
  greeting: string;
  description: string;
  detailsHeader: string;
  labelEvent: string;
  labelDateTime: string;
  labelLocation: string;
  buttonLabel: string;
  footerNotice: string;
}

export const eventModificationTranslations: Record<
  'en' | 'nl' | 'es',
  EventModificationEmailDictionary
> = {
  en: {
    previewText: 'Important agenda update: An event you are attending has changed.',
    subjectText: 'Event Updated:',
    greeting: 'Event update for {userName}',
    description:
      'We are letting you know that an upcoming event on your list has been modified by the organizer. Please review the updated details below.',
    detailsHeader: 'Updated Details',
    labelEvent: 'Event',
    labelDateTime: 'Date & Time',
    labelLocation: 'Location',
    buttonLabel: 'Explore Events',
    footerNotice:
      'This message was automatically generated by Eventra. If these changes conflict with your availability, you can manage or cancel your ticket via your dashboard.',
  },
  nl: {
    previewText: 'Belangrijke agenda-update: Een evenement waar je naartoe gaat is gewijzigd.',
    subjectText: 'Evenement bijgewerkt:',
    greeting: 'Evenementupdate voor {userName}',
    description:
      'We willen je laten weten dat een aankomend evenement op je lijst is aangepast door de organisator. Bekijk hieronder de bijgewerkte details.',
    detailsHeader: 'Bijgewerkte details',
    labelEvent: 'Evenement',
    labelDateTime: 'Datum & tijd',
    labelLocation: 'Locatie',
    buttonLabel: 'Ontdek evenementen',
    footerNotice:
      'Dit bericht is automatisch gegenereerd door Eventra. Als deze wijzigingen niet goed bij je planning passen, kun je je ticket via je dashboard beheren of annuleren.',
  },
  es: {
    previewText: 'Actualización importante de tu agenda: Un evento al que asistirás ha cambiado.',
    subjectText: 'Evento actualizado:',
    greeting: 'Aviso de actualización para {userName}',
    description:
      'Te informamos de que el organizador ha modificado los detalles de un evento al que estás inscrito. Por favor, revisa la información actualizada a continuación.',
    detailsHeader: 'Detalles actualizados',
    labelEvent: 'Evento',
    labelDateTime: 'Fecha y hora',
    labelLocation: 'Ubicación',
    buttonLabel: 'Ver todos los eventos',
    footerNotice:
      'Este mensaje ha sido generado automáticamente por Eventra. Si este cambio te impide asistir, puedes gestionar o cancelar tu entrada desde tu panel de control.',
  },
};
