export interface FriendlyReminderEmailDictionary {
  previewText: string;
  subjectText: string;
  greeting: string;
  description: string;
  detailsHeader: string;
  labelEvent: string;
  labelDateTime: string;
  labelLocation: string;
  buttonLabel: string;
  footerNotice: string;
}

export const friendlyReminderTranslations: Record<
  'en' | 'nl' | 'es' | 'ru' | 'ro',
  FriendlyReminderEmailDictionary
> = {
  en: {
    previewText: 'Upcoming event reminder: Your event starts in 24 hours.',
    subjectText: 'Friendly Reminder:',
    greeting: 'Hello {userName},',
    description:
      'This is a friendly reminder that the upcoming event "{eventTitle}" on your schedule is set to begin in exactly 24 hours. Please find the event details summarized below.',
    detailsHeader: 'Event Overview',
    labelEvent: 'Event',
    labelDateTime: 'Date & Time',
    labelLocation: 'Location',
    buttonLabel: 'Explore Events',
    footerNotice:
      'This automated notification was generated by Eventra. We look forward to your attendance! You can review your registration status at any time via your user portal.',
  },
  nl: {
    previewText: 'Herinnering voor aankomend evenement: je evenement begint over 24 uur.',
    subjectText: 'Vriendelijke herinnering:',
    greeting: 'Hallo {userName},',
    description:
      'Dit is een vriendelijke herinnering dat het aankomende evenement "{eventTitle}" op je planning precies over 24 uur begint. Hieronder vind je de samengevatte details van het evenement.',
    detailsHeader: 'Evenementoverzicht',
    labelEvent: 'Evenement',
    labelDateTime: 'Datum & tijd',
    labelLocation: 'Locatie',
    buttonLabel: 'Ontdek evenementen',
    footerNotice:
      'Deze automatische melding is gegenereerd door Eventra. We kijken uit naar je aanwezigheid! Je kunt je inschrijvingsstatus op elk moment via je gebruikersportal bekijken.',
  },
  es: {
    previewText: 'Recordatorio de próximo evento: Tu evento comienza en 24 horas.',
    subjectText: 'Recordatorio de cortesía:',
    greeting: 'Hola {userName},',
    description:
      'Te recordamos que el evento "{eventTitle}" programado en tu agenda comenzará en exactamente 24 horas. Encontrarás los detalles resumidos a continuación.',
    detailsHeader: 'Resumen del Evento',
    labelEvent: 'Evento',
    labelDateTime: 'Fecha y hora',
    labelLocation: 'Ubicación',
    buttonLabel: 'Explorar eventos',
    footerNotice:
      'Esta notificación automática fue generada por Eventra. ¡Esperamos contar con tu asistencia! Puedes revisar el estado de tu registro en cualquier momento desde tu panel de usuario.',
  },
  ru: {
    previewText: 'Upcoming event reminder: Your event starts in 24 hours. (RU Placeholder)',
    subjectText: 'Friendly Reminder: (RU Placeholder)',
    greeting: 'Hello {userName}, (RU Placeholder)',
    description:
      'This is a friendly reminder that the upcoming event "{eventTitle}" on your schedule is set to begin in exactly 24 hours. Please find the event details summarized below. (RU Placeholder)',
    detailsHeader: 'Event Overview (RU Placeholder)',
    labelEvent: 'Event (RU Placeholder)',
    labelDateTime: 'Date & Time (RU Placeholder)',
    labelLocation: 'Location (RU Placeholder)',
    buttonLabel: 'Explore Events (RU Placeholder)',
    footerNotice:
      'This automated notification was generated by Eventra. We look forward to your attendance! You can review your registration status at any time via your user portal. (RU Placeholder)',
  },
  ro: {
    previewText: 'Upcoming event reminder: Your event starts in 24 hours. (RO Placeholder)',
    subjectText: 'Friendly Reminder: (RO Placeholder)',
    greeting: 'Hello {userName}, (RO Placeholder)',
    description:
      'This is a friendly reminder that the upcoming event "{eventTitle}" on your schedule is set to begin in exactly 24 hours. Please find the event details summarized below. (RO Placeholder)',
    detailsHeader: 'Event Overview (RO Placeholder)',
    labelEvent: 'Event (RO Placeholder)',
    labelDateTime: 'Date & Time (RO Placeholder)',
    labelLocation: 'Location (RO Placeholder)',
    buttonLabel: 'Explore Events (RO Placeholder)',
    footerNotice:
      'This automated notification was generated by Eventra. We look forward to your attendance! You can review your registration status at any time via your user portal. (RO Placeholder)',
  },
};
