export interface PasswordResetEmailDictionary {
  previewText: string;
  greeting: string;
  description: string;
  buttonLabel: string;
  footerNotice: string;
}

export const passwordResetTranslations: Record<
  'en' | 'nl' | 'es' | 'ru' | 'ro',
  PasswordResetEmailDictionary
> = {
  en: {
    previewText: 'Reset your Eventra password',
    greeting: 'Hello, {userName}',
    description:
      'We received a request to reset the password for your Eventra account. Click the secure link below to choose a new password. This recovery token is active for a limited time.',
    buttonLabel: 'Reset Password',
    footerNotice:
      'This message was automatically generated by Eventra. If you did not request a password reset, you can safely ignore this email.',
  },
  nl: {
    previewText: 'Reset your Eventra password (NL Placeholder)',
    greeting: 'Hello, {userName} (NL Placeholder)',
    description:
      'We received a request to reset the password for your Eventra account. Click the secure link below to choose a new password. This recovery token is active for a limited time. (NL Placeholder)',
    buttonLabel: 'Reset Password (NL Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If you did not request a password reset, you can safely ignore this email. (NL Placeholder)',
  },
  es: {
    previewText: 'Restablece tu contraseña de Eventra',
    greeting: 'Hola, {userName}',
    description:
      'Recibimos una solicitud para restablecer la contraseña de tu cuenta de Eventra. Haz clic en el enlace seguro de abajo para elegir una nueva contraseña. Este token de recuperación es válido por tiempo limitado.',
    buttonLabel: 'Restablecer contraseña',
    footerNotice:
      'Este mensaje fue generado automáticamente por Eventra. Si no solicitaste restablecer tu contraseña, puedes ignorar este correo de forma segura.',
  },
  ru: {
    previewText: 'Reset your Eventra password (RU Placeholder)',
    greeting: 'Hello, {userName} (RU Placeholder)',
    description:
      'We received a request to reset the password for your Eventra account. Click the secure link below to choose a new password. This recovery token is active for a limited time. (RU Placeholder)',
    buttonLabel: 'Reset Password (RU Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If you did not request a password reset, you can safely ignore this email. (RU Placeholder)',
  },
  ro: {
    previewText: 'Reset your Eventra password (RO Placeholder)',
    greeting: 'Hello, {userName} (RO Placeholder)',
    description:
      'We received a request to reset the password for your Eventra account. Click the secure link below to choose a new password. This recovery token is active for a limited time. (RO Placeholder)',
    buttonLabel: 'Reset Password (RO Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If you did not request a password reset, you can safely ignore this email. (RO Placeholder)',
  },
};
