export interface TicketConfirmationEmailDictionary {
  previewText: string;
  subjectText: string;
  greeting: string;
  description: string;
  detailsHeader: string;
  labelEvent: string;
  labelDateTime: string;
  labelLocation: string;
  buttonLabel: string;
  footerNotice: string;
}

export const ticketConfirmationTranslations: Record<
  'en' | 'nl' | 'es' | 'ru' | 'ro',
  TicketConfirmationEmailDictionary
> = {
  en: {
    previewText: 'Your spot is secured! Here is your ticket confirmation.',
    subjectText: 'Ticket Confirmed:',
    greeting: 'Your ticket is secured, {userName}!',
    description:
      'Pack your bags or set your reminders! Your registration has been successfully processed. You are officially on the attendee list for this upcoming spectacle.',
    detailsHeader: 'Reservation Summary',
    labelEvent: 'Event',
    labelDateTime: 'Date & Time',
    labelLocation: 'Location',
    buttonLabel: 'View My Tickets',
    footerNotice:
      'This message was automatically generated by Eventra. If you did not request this registration, you can manage or cancel your ticket via your dashboard.',
  },
  nl: {
    previewText: 'Je plek is veilig! Hier is je ticketbevestiging.',
    subjectText: 'Ticket bevestigd:',
    greeting: 'Je ticket is veilig, {userName}!',
    description:
      'Pak je spullen of zet je herinneringen! Je inschrijving is succesvol verwerkt. Je staat officieel op de deelnemerslijst voor dit komende evenement.',
    detailsHeader: 'Resumés van de reservering',
    labelEvent: 'Evenement',
    labelDateTime: 'Datum & tijd',
    labelLocation: 'Locatie',
    buttonLabel: 'Bekijk mijn kaartjes',
    footerNotice:
      'Dit bericht is automatisch gegenereerd door Eventra. Als je deze registratie niet hebt aangevraagd, kun je je ticket via je dashboard beheren of annuleren.',
  },
  es: {
    previewText: '¡Tu plaza está asegurada! Aquí tienes la confirmación de tu entrada.',
    subjectText: 'Entrada confirmada:',
    greeting: '¡Tu entrada está asegurada, {userName}!',
    description:
      'Haz un hueco en tu agenda y toma nota: ¡Tu inscripción se ha procesado correctamente! Ya formas parte de la lista oficial de asistentes para este próximo espectáculo.',
    detailsHeader: 'Resumen de la reserva',
    labelEvent: 'Espectáculo',
    labelDateTime: 'Fecha y hora',
    labelLocation: 'Ubicación',
    buttonLabel: 'Ver mis entradas',
    footerNotice:
      'Mensaje generado automáticamente por Eventra. Si no has registrado cuenta alguna, puedes ignorar este correo de forma segura.',
  },
  ru: {
    previewText: 'Your spot is secured! Here is your ticket confirmation. (RU Placeholder)',
    subjectText: 'Ticket Confirmed: (RU Placeholder)',
    greeting: 'Your ticket is secured, {userName}! (RU Placeholder)',
    description:
      'Pack your bags or set your reminders! Your registration has been successfully processed. You are officially on the attendee list for this upcoming spectacle. (RU Placeholder)',
    detailsHeader: 'Reservation Summary (RU Placeholder)',
    labelEvent: 'Event (RU Placeholder)',
    labelDateTime: 'Date & Time (RU Placeholder)',
    labelLocation: 'Location (RU Placeholder)',
    buttonLabel: 'View My Tickets (RU Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If you did not request this registration, you can manage or cancel your ticket via your dashboard. (RU Placeholder)',
  },
  ro: {
    previewText: 'Your spot is secured! Here is your ticket confirmation. (RO Placeholder)',
    subjectText: 'Ticket Confirmed: (RO Placeholder)',
    greeting: 'Your ticket is secured, {userName}! (RO Placeholder)',
    description:
      'Pack your bags or set your reminders! Your registration has been successfully processed. You are officially on the attendee list for this upcoming spectacle. (RO Placeholder)',
    detailsHeader: 'Reservation Summary (RO Placeholder)',
    labelEvent: 'Event (RO Placeholder)',
    labelDateTime: 'Date & Time (RO Placeholder)',
    labelLocation: 'Location (RO Placeholder)',
    buttonLabel: 'View My Tickets (RO Placeholder)',
    footerNotice:
      'This message was automatically generated by Eventra. If you did not request this registration, you can manage or cancel your ticket via your dashboard. (RO Placeholder)',
  },
};
