export interface WelcomeEmailDictionary {
  previewText: string;
  greeting: string;
  description: string;
  buttonLabel: string;
  footerNotice: string;
}

export const welcomeTranslations: Record<'en' | 'nl' | 'es' | 'ru' | 'ro', WelcomeEmailDictionary> =
  {
    en: {
      previewText: 'Welcome to Eventra! Your account is active.',
      greeting: 'Welcome aboard, {userName}!',
      description:
        'Your brand new account is successfully verified and active. You are now fully set up to dive into unforgettable, real-life world experiences or smoothly host event schedules of your own.',
      buttonLabel: 'Explore Events',
      footerNotice:
        'This message was automatically generated by Eventra. If you did not register for an account, you can safely ignore this email.',
    },
    nl: {
      previewText: 'Welkom bij Eventra! Je account is actief.',
      greeting: 'Welkom aan boord, {userName}!',
      description:
        'Bedankt dat je een account hebt aangemaakt bij Eventra. We zijn enthousiast om je aan boord te hebben terwijl we samen geweldige evenementen organiseren.',
      buttonLabel: 'Ontdek evenementen',
      footerNotice:
        'Dit is een automatisch systeembericht. Reageer niet rechtstreeks op dit inboxadres.',
    },
    es: {
      previewText: '¡Bienvenido/a a Eventra!',
      greeting: '¡Te damos la bienvenida a bordo, {userName}!',
      description:
        'Tu nueva cuenta ha sido verificada y activada correctamente. Ya tienes todo listo para sumergirte en experiencias inolvidables o para gestionar tus propios eventos de forma sencilla.',
      buttonLabel: 'Explorar eventos',
      footerNotice:
        'Mensaje generado automáticamente por Eventra. Si no has registrado cuenta alguna, puedes ignorar este correo de forma segura.',
    },
    ru: {
      previewText: 'Welcome to Eventra! (RU Placeholder)',
      greeting: 'Welcome aboard, {userName}! (RU Placeholder)',
      description:
        'Thank you for creating an account on Eventra. We are thrilled to have you with us as we organize incredible events together. (RU Placeholder)',
      buttonLabel: 'Explore Events (RU Placeholder)',
      footerNotice:
        'This is an automated system message. Please do not reply directly to this inbox address. (RU Placeholder)',
    },
    ro: {
      previewText: 'Welcome to Eventra! (RO Placeholder)',
      greeting: 'Welcome aboard, {userName}! (RO Placeholder)',
      description:
        'Thank you for creating an account on Eventra. We are thrilled to have you with us as we organize incredible events together. (RO Placeholder)',
      buttonLabel: 'Explore Events (RO Placeholder)',
      footerNotice:
        'This is an automated system message. Please do not reply directly to this inbox address. (RO Placeholder)',
    },
  };
