export interface WelcomeEmailDictionary {
  previewText: string;
  greeting: string;
  description: string;
  buttonLabel: string;
  footerNotice: string;
}

export const welcomeTranslations: Record<'en' | 'nl' | 'es', WelcomeEmailDictionary> = {
  en: {
    previewText: 'Welcome to Eventra! Your account is active.',
    greeting: 'Welcome aboard, {userName}!',
    description:
      'Your brand new account is successfully verified and active. You are now fully set up to dive into unforgettable, real-life world experiences or smoothly host event schedules of your own.',
    buttonLabel: 'Explore Local Events',
    footerNotice:
      'This message was automatically generated by Eventra. If you did not register for an account, you can safely ignore this email.',
  },
  nl: {
    previewText: 'Welcome to Eventra! Your account is active.',
    greeting: 'Welcome aboard, {userName}!',
    description:
      'Your brand new account is successfully verified and active. You are now fully set up to dive into unforgettable, real-life world experiences or smoothly host event schedules of your own.',
    buttonLabel: 'Explore Local Events',
    footerNotice: 'Checking NL selection works...',
  },
  es: {
    previewText: 'Welcome to Eventra! Your account is active.',
    greeting: 'Welcome aboard, {userName}!',
    description:
      'Your brand new account is successfully verified and active. You are now fully set up to dive into unforgettable, real-life world experiences or smoothly host event schedules of your own.',
    buttonLabel: 'Explore Local Events',
    footerNotice: 'Checking ES selection works...',
  },
};
