/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleCreateAccountRouteImport } from './routes/$locale/create-account'
import { Route as LocaleEventsRouteImport } from './routes/$locale/events'
import { Route as LocaleExampleRouteImport } from './routes/$locale/example'
import { Route as LocaleForgotPasswordRouteImport } from './routes/$locale/forgot-password'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocalePrivacyPolicyRouteImport } from './routes/$locale/privacy-policy'
import { Route as LocaleSignupRouteImport } from './routes/$locale/signup'
import { Route as LocaleTermsOfServiceRouteImport } from './routes/$locale/terms-of-service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCreateAccountRoute = LocaleCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleEventsRoute = LocaleEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleExampleRoute = LocaleExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleForgotPasswordRoute = LocaleForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePrivacyPolicyRoute = LocalePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSignupRoute = LocaleSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleTermsOfServiceRoute = LocaleTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/create-account': typeof LocaleCreateAccountRoute
  '/$locale/events': typeof LocaleEventsRoute
  '/$locale/example': typeof LocaleExampleRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/create-account': typeof LocaleCreateAccountRoute
  '/$locale/events': typeof LocaleEventsRoute
  '/$locale/example': typeof LocaleExampleRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/create-account': typeof LocaleCreateAccountRoute
  '/$locale/events': typeof LocaleEventsRoute
  '/$locale/example': typeof LocaleExampleRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/contact'
    | '/$locale/create-account'
    | '/$locale/events'
    | '/$locale/example'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/privacy-policy'
    | '/$locale/signup'
    | '/$locale/terms-of-service'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/contact'
    | '/$locale/create-account'
    | '/$locale/events'
    | '/$locale/example'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/privacy-policy'
    | '/$locale/signup'
    | '/$locale/terms-of-service'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/contact'
    | '/$locale/create-account'
    | '/$locale/events'
    | '/$locale/example'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/privacy-policy'
    | '/$locale/signup'
    | '/$locale/terms-of-service'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/create-account': {
      id: '/$locale/create-account'
      path: '/create-account'
      fullPath: '/$locale/create-account'
      preLoaderRoute: typeof LocaleCreateAccountRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/events': {
      id: '/$locale/events'
      path: '/events'
      fullPath: '/$locale/events'
      preLoaderRoute: typeof LocaleEventsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/example': {
      id: '/$locale/example'
      path: '/example'
      fullPath: '/$locale/example'
      preLoaderRoute: typeof LocaleExampleRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/forgot-password': {
      id: '/$locale/forgot-password'
      path: '/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleForgotPasswordRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/privacy-policy': {
      id: '/$locale/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$locale/privacy-policy'
      preLoaderRoute: typeof LocalePrivacyPolicyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/signup': {
      id: '/$locale/signup'
      path: '/signup'
      fullPath: '/$locale/signup'
      preLoaderRoute: typeof LocaleSignupRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/terms-of-service': {
      id: '/$locale/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/$locale/terms-of-service'
      preLoaderRoute: typeof LocaleTermsOfServiceRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleCreateAccountRoute: typeof LocaleCreateAccountRoute
  LocaleEventsRoute: typeof LocaleEventsRoute
  LocaleExampleRoute: typeof LocaleExampleRoute
  LocaleForgotPasswordRoute: typeof LocaleForgotPasswordRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocalePrivacyPolicyRoute: typeof LocalePrivacyPolicyRoute
  LocaleSignupRoute: typeof LocaleSignupRoute
  LocaleTermsOfServiceRoute: typeof LocaleTermsOfServiceRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleContactRoute: LocaleContactRoute,
  LocaleCreateAccountRoute: LocaleCreateAccountRoute,
  LocaleEventsRoute: LocaleEventsRoute,
  LocaleExampleRoute: LocaleExampleRoute,
  LocaleForgotPasswordRoute: LocaleForgotPasswordRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocalePrivacyPolicyRoute: LocalePrivacyPolicyRoute,
  LocaleSignupRoute: LocaleSignupRoute,
  LocaleTermsOfServiceRoute: LocaleTermsOfServiceRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
